### ISSUE TITLE
Align fields in left and right columns in Edit form

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#153]
The fields in the left and right columns of the metadata entry (edit) forms are slightly misaligned.  See screenshots below of Collection and Work forms.

<img width="1162" alt="wustl 153 - edit form alignment - collections" src="https://cloud.githubusercontent.com/assets/3064318/10200186/8937e1cc-676a-11e5-8ce1-9d01d9bf5d47.png">
<img width="1171" alt="wustl 153 - edit form alignment - works" src="https://cloud.githubusercontent.com/assets/3064318/10200185/8936b52c-676a-11e5-9906-4713355acad4.png">

**Comment by jcoyne** [comment]
This is because "Title" has an abbr element before it with a font size of 1.25em

``` css
/* line 67, /Users/justin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/curation_concerns-1d39808082d6/app/assets/stylesheets/curation_concerns/modules/forms.scss */
.control-label.required abbr {
  font-size: 1.25em;
  font-weight: bold;
}
```
